// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SideSeat.Data;

#nullable disable

namespace SideSeat.Migrations
{
    [DbContext(typeof(SideSeatDbContext))]
    [Migration("20260521133144_ExpandSeedData")]
    partial class ExpandSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SideSeat.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Gradovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Drzava = "Hrvatska",
                            Naziv = "Zagreb",
                            PostanskiBroj = "10000"
                        },
                        new
                        {
                            Id = 2,
                            Drzava = "Hrvatska",
                            Naziv = "Split",
                            PostanskiBroj = "21000"
                        },
                        new
                        {
                            Id = 3,
                            Drzava = "Hrvatska",
                            Naziv = "Rijeka",
                            PostanskiBroj = "51000"
                        },
                        new
                        {
                            Id = 4,
                            Drzava = "Hrvatska",
                            Naziv = "Osijek",
                            PostanskiBroj = "31000"
                        },
                        new
                        {
                            Id = 5,
                            Drzava = "Hrvatska",
                            Naziv = "Zadar",
                            PostanskiBroj = "23000"
                        },
                        new
                        {
                            Id = 6,
                            Drzava = "Hrvatska",
                            Naziv = "Pula",
                            PostanskiBroj = "52100"
                        },
                        new
                        {
                            Id = 7,
                            Drzava = "Hrvatska",
                            Naziv = "Slavonski Brod",
                            PostanskiBroj = "35000"
                        },
                        new
                        {
                            Id = 8,
                            Drzava = "Hrvatska",
                            Naziv = "Karlovac",
                            PostanskiBroj = "47000"
                        },
                        new
                        {
                            Id = 9,
                            Drzava = "Hrvatska",
                            Naziv = "Varazdin",
                            PostanskiBroj = "42000"
                        },
                        new
                        {
                            Id = 10,
                            Drzava = "Hrvatska",
                            Naziv = "Sibenik",
                            PostanskiBroj = "22000"
                        },
                        new
                        {
                            Id = 11,
                            Drzava = "Hrvatska",
                            Naziv = "Dubrovnik",
                            PostanskiBroj = "20000"
                        },
                        new
                        {
                            Id = 12,
                            Drzava = "Hrvatska",
                            Naziv = "Sisak",
                            PostanskiBroj = "44000"
                        },
                        new
                        {
                            Id = 13,
                            Drzava = "Hrvatska",
                            Naziv = "Vukovar",
                            PostanskiBroj = "32000"
                        },
                        new
                        {
                            Id = 14,
                            Drzava = "Hrvatska",
                            Naziv = "Bjelovar",
                            PostanskiBroj = "43000"
                        },
                        new
                        {
                            Id = 15,
                            Drzava = "Hrvatska",
                            Naziv = "Koprivnica",
                            PostanskiBroj = "48000"
                        },
                        new
                        {
                            Id = 16,
                            Drzava = "Hrvatska",
                            Naziv = "Cakovec",
                            PostanskiBroj = "40000"
                        },
                        new
                        {
                            Id = 17,
                            Drzava = "Hrvatska",
                            Naziv = "Vinkovci",
                            PostanskiBroj = "32100"
                        },
                        new
                        {
                            Id = 18,
                            Drzava = "Hrvatska",
                            Naziv = "Makarska",
                            PostanskiBroj = "21300"
                        },
                        new
                        {
                            Id = 19,
                            Drzava = "Hrvatska",
                            Naziv = "Samobor",
                            PostanskiBroj = "10430"
                        },
                        new
                        {
                            Id = 20,
                            Drzava = "Hrvatska",
                            Naziv = "Velika Gorica",
                            PostanskiBroj = "10410"
                        },
                        new
                        {
                            Id = 21,
                            Drzava = "Hrvatska",
                            Naziv = "Kastela",
                            PostanskiBroj = "21210"
                        },
                        new
                        {
                            Id = 22,
                            Drzava = "Hrvatska",
                            Naziv = "Pozega",
                            PostanskiBroj = "34000"
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojMobitela")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("bit");

                    b.Property<string>("KycBrojOsobne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KycBrojVozacke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KycDatumRodenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("KycOib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KycPodnesen")
                        .HasColumnType("bit");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoziloId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresa = "Ilica 10, Zagreb",
                            BrojMobitela = "0911111111",
                            DatumRegistracije = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko@example.com",
                            Ime = "Marko",
                            JeAktivan = true,
                            KycBrojOsobne = "12345678",
                            KycBrojVozacke = "HR-VOZ-001",
                            KycDatumRodenja = new DateTime(1990, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KycOib = "12345678901",
                            KycPodnesen = true,
                            LozinkaHash = "WjgcARlXlANvPrwzymGupw==.mAJGLSfwA1qBVtNB5RA7flpqKTF6m4GaYykrX7DvfRM=",
                            Prezime = "Maric",
                            Tip = 0
                        },
                        new
                        {
                            Id = 2,
                            Adresa = "Marmontova 21, Split",
                            BrojMobitela = "0922222222",
                            DatumRegistracije = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivana@example.com",
                            Ime = "Ivana",
                            JeAktivan = true,
                            KycPodnesen = false,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Ivic",
                            Tip = 1
                        },
                        new
                        {
                            Id = 3,
                            Adresa = "Savska 100, Zagreb",
                            BrojMobitela = "0933333333",
                            DatumRegistracije = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            Ime = "Ana",
                            JeAktivan = true,
                            KycPodnesen = true,
                            LozinkaHash = "UJon3KrOrz+TJuEAH49PBA==.mtr30yYsJ5J4MS/edvNKLbZ/aOhiZ+W0gPp24rGz0JY=",
                            Prezime = "Admin",
                            Tip = 2
                        },
                        new
                        {
                            Id = 4,
                            Adresa = "Korzo 1, Rijeka",
                            BrojMobitela = "0941111111",
                            DatumRegistracije = new DateTime(2026, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petar@example.com",
                            Ime = "Petar",
                            JeAktivan = true,
                            KycPodnesen = true,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Peric",
                            Tip = 0
                        },
                        new
                        {
                            Id = 5,
                            Adresa = "Tvrda 12, Osijek",
                            BrojMobitela = "0951111111",
                            DatumRegistracije = new DateTime(2026, 5, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "maja@example.com",
                            Ime = "Maja",
                            JeAktivan = true,
                            KycPodnesen = false,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Matic",
                            Tip = 1
                        },
                        new
                        {
                            Id = 6,
                            Adresa = "Poluotok 3, Zadar",
                            BrojMobitela = "0961111111",
                            DatumRegistracije = new DateTime(2026, 5, 4, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "luka@example.com",
                            Ime = "Luka",
                            JeAktivan = true,
                            KycPodnesen = true,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Lukic",
                            Tip = 3
                        },
                        new
                        {
                            Id = 7,
                            Adresa = "Forum 5, Pula",
                            BrojMobitela = "0971111111",
                            DatumRegistracije = new DateTime(2026, 5, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "iva@example.com",
                            Ime = "Iva",
                            JeAktivan = true,
                            KycPodnesen = false,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Ilic",
                            Tip = 1
                        },
                        new
                        {
                            Id = 8,
                            Adresa = "Centar 20, Karlovac",
                            BrojMobitela = "0981111111",
                            DatumRegistracije = new DateTime(2026, 5, 5, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "dino@example.com",
                            Ime = "Dino",
                            JeAktivan = true,
                            KycPodnesen = true,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Doric",
                            Tip = 0
                        },
                        new
                        {
                            Id = 9,
                            Adresa = "Centar 8, Sisak",
                            BrojMobitela = "0991111111",
                            DatumRegistracije = new DateTime(2026, 5, 6, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikolina@example.com",
                            Ime = "Nikolina",
                            JeAktivan = true,
                            KycPodnesen = false,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Ninic",
                            Tip = 1
                        },
                        new
                        {
                            Id = 10,
                            Adresa = "Riva 2, Sibenik",
                            BrojMobitela = "0912222222",
                            DatumRegistracije = new DateTime(2026, 5, 7, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "filip@example.com",
                            Ime = "Filip",
                            JeAktivan = true,
                            KycPodnesen = true,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Filic",
                            Tip = 3
                        },
                        new
                        {
                            Id = 11,
                            Adresa = "Stari grad 4, Dubrovnik",
                            BrojMobitela = "0923333333",
                            DatumRegistracije = new DateTime(2026, 5, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sandra@example.com",
                            Ime = "Sandra",
                            JeAktivan = true,
                            KycPodnesen = false,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Soric",
                            Tip = 1
                        },
                        new
                        {
                            Id = 12,
                            Adresa = "Centar 44, Varazdin",
                            BrojMobitela = "0934444444",
                            DatumRegistracije = new DateTime(2026, 5, 8, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "tomislav@example.com",
                            Ime = "Tomislav",
                            JeAktivan = true,
                            KycPodnesen = true,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Tomic",
                            Tip = 0
                        },
                        new
                        {
                            Id = 13,
                            Adresa = "Centar 5, Slavonski Brod",
                            BrojMobitela = "0945555555",
                            DatumRegistracije = new DateTime(2026, 5, 8, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "marina@example.com",
                            Ime = "Marina",
                            JeAktivan = true,
                            KycPodnesen = false,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Marinic",
                            Tip = 1
                        },
                        new
                        {
                            Id = 14,
                            Adresa = "Nova cesta 14, Samobor",
                            BrojMobitela = "0956666666",
                            DatumRegistracije = new DateTime(2026, 5, 9, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bruno@example.com",
                            Ime = "Bruno",
                            JeAktivan = true,
                            KycPodnesen = true,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Brnic",
                            Tip = 0
                        },
                        new
                        {
                            Id = 15,
                            Adresa = "Luka 12, Makarska",
                            BrojMobitela = "0967777777",
                            DatumRegistracije = new DateTime(2026, 5, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lea@example.com",
                            Ime = "Lea",
                            JeAktivan = true,
                            KycPodnesen = false,
                            LozinkaHash = "d+Ekke4YV8yR6E71CavL1w==.emo+8SBlglGcaUZ6zdYXv/sWOHz95xzNsKI3rkmB8os=",
                            Prezime = "Lelic",
                            Tip = 1
                        });
                });

            modelBuilder.Entity("SideSeat.Models.OcjenaVoznje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("BrojZvjezdica")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kreirano")
                        .HasColumnType("datetime2");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("Ocjene");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 2,
                            BrojZvjezdica = 5,
                            Komentar = "Odlicno",
                            Kreirano = new DateTime(2026, 5, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            RezervacijaId = 1
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<bool>("Uspjesno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VrijemePlacanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("Placanja");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Iznos = 15.00m,
                            NacinPlacanja = 1,
                            RezervacijaId = 1,
                            Uspjesno = true,
                            VrijemePlacanja = new DateTime(2026, 5, 2, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojMjesta")
                        .HasColumnType("int");

                    b.Property<decimal>("CijenaUkupno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PutnikId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VoznjaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemeRezervacije")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PutnikId");

                    b.HasIndex("VoznjaId");

                    b.ToTable("Rezervacije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojMjesta = 1,
                            CijenaUkupno = 15.00m,
                            Napomena = "Bez prtljage",
                            PutnikId = 2,
                            Status = 0,
                            VoznjaId = 1,
                            VrijemeRezervacije = new DateTime(2026, 5, 2, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Vozilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("BrojSjedala")
                        .HasColumnType("int");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("ProsjecnaPotrosnja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Registracija")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int?>("VlasnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VlasnikId");

                    b.ToTable("Vozila");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Boja = "Siva",
                            BrojSjedala = 5,
                            GodinaProizvodnje = 2021,
                            Marka = "Skoda",
                            Model = "Octavia",
                            ProsjecnaPotrosnja = 6.5m,
                            Registracija = "ZG-1234-AA",
                            VlasnikId = 1
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoMjestu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OcekivaniDolazak")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdredisniGradId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Polazak")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolazniGradId")
                        .HasColumnType("int");

                    b.Property<int>("SlobodnaMjesta")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UkupnoMjesta")
                        .HasColumnType("int");

                    b.Property<int>("VozacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdredisniGradId");

                    b.HasIndex("PolazniGradId");

                    b.HasIndex("VozacId");

                    b.ToTable("Voznje");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CijenaPoMjestu = 15.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 2,
                            Opis = "Jutarnja voznja",
                            Polazak = new DateTime(2026, 5, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 1,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 1
                        },
                        new
                        {
                            Id = 2,
                            CijenaPoMjestu = 12.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 11, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 1,
                            Opis = "Rijeka - Zagreb",
                            Polazak = new DateTime(2026, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 3,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 4
                        },
                        new
                        {
                            Id = 3,
                            CijenaPoMjestu = 10.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 2,
                            Opis = "Popodnevna voznja",
                            Polazak = new DateTime(2026, 5, 11, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 5,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 6
                        },
                        new
                        {
                            Id = 4,
                            CijenaPoMjestu = 8.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 1,
                            Opis = "Karlovac -> Zagreb",
                            Polazak = new DateTime(2026, 5, 12, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 8,
                            SlobodnaMjesta = 1,
                            Status = 0,
                            UkupnoMjesta = 3,
                            VozacId = 8
                        },
                        new
                        {
                            Id = 5,
                            CijenaPoMjestu = 9.50m,
                            OcekivaniDolazak = new DateTime(2026, 5, 12, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 2,
                            Opis = "Jutarnji prijevoz",
                            Polazak = new DateTime(2026, 5, 12, 6, 50, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 10,
                            SlobodnaMjesta = 4,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 10
                        },
                        new
                        {
                            Id = 6,
                            CijenaPoMjestu = 11.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 12, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 1,
                            Opis = "Varazdin -> Zagreb",
                            Polazak = new DateTime(2026, 5, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 9,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 12
                        },
                        new
                        {
                            Id = 7,
                            CijenaPoMjestu = 6.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 13, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 1,
                            Opis = "Samobor shuttle",
                            Polazak = new DateTime(2026, 5, 13, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 19,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 3,
                            VozacId = 14
                        },
                        new
                        {
                            Id = 8,
                            CijenaPoMjestu = 5.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 13, 17, 55, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 20,
                            Opis = "ZG -> VG",
                            Polazak = new DateTime(2026, 5, 13, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 1,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 1
                        },
                        new
                        {
                            Id = 9,
                            CijenaPoMjestu = 10.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 14, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 6,
                            Opis = "Rijeka -> Pula",
                            Polazak = new DateTime(2026, 5, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 3,
                            SlobodnaMjesta = 4,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 4
                        },
                        new
                        {
                            Id = 10,
                            CijenaPoMjestu = 4.50m,
                            OcekivaniDolazak = new DateTime(2026, 5, 14, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 21,
                            Opis = "Split -> Kastela",
                            Polazak = new DateTime(2026, 5, 14, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 2,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 6
                        },
                        new
                        {
                            Id = 11,
                            CijenaPoMjestu = 9.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 15, 8, 50, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 12,
                            Opis = "Karlovac -> Sisak",
                            Polazak = new DateTime(2026, 5, 15, 7, 40, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 8,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 3,
                            VozacId = 8
                        },
                        new
                        {
                            Id = 12,
                            CijenaPoMjestu = 8.50m,
                            OcekivaniDolazak = new DateTime(2026, 5, 15, 14, 55, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 5,
                            Opis = "Sibenik -> Zadar",
                            Polazak = new DateTime(2026, 5, 15, 13, 25, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 10,
                            SlobodnaMjesta = 1,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 10
                        },
                        new
                        {
                            Id = 13,
                            CijenaPoMjestu = 6.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 15, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 15,
                            Opis = "Varazdin -> Koprivnica",
                            Polazak = new DateTime(2026, 5, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 9,
                            SlobodnaMjesta = 4,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 12
                        },
                        new
                        {
                            Id = 14,
                            CijenaPoMjestu = 9.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 16, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 8,
                            Opis = "Samobor -> Karlovac",
                            Polazak = new DateTime(2026, 5, 16, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 19,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 3,
                            VozacId = 14
                        },
                        new
                        {
                            Id = 15,
                            CijenaPoMjestu = 16.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 16, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 4,
                            Opis = "Zagreb -> Osijek",
                            Polazak = new DateTime(2026, 5, 16, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 1,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 1
                        },
                        new
                        {
                            Id = 16,
                            CijenaPoMjestu = 18.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 10,
                            Opis = "Rijeka -> Sibenik",
                            Polazak = new DateTime(2026, 5, 16, 17, 10, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 3,
                            SlobodnaMjesta = 4,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 4
                        },
                        new
                        {
                            Id = 17,
                            CijenaPoMjestu = 7.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 17, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 18,
                            Opis = "Split -> Makarska",
                            Polazak = new DateTime(2026, 5, 17, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 2,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 6
                        },
                        new
                        {
                            Id = 18,
                            CijenaPoMjestu = 14.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 17, 15, 5, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 22,
                            Opis = "Karlovac -> Pozega",
                            Polazak = new DateTime(2026, 5, 17, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 8,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 3,
                            VozacId = 8
                        },
                        new
                        {
                            Id = 19,
                            CijenaPoMjestu = 20.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 18, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 11,
                            Opis = "Sibenik -> Dubrovnik",
                            Polazak = new DateTime(2026, 5, 18, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 10,
                            SlobodnaMjesta = 1,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 10
                        },
                        new
                        {
                            Id = 20,
                            CijenaPoMjestu = 5.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 18, 15, 35, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 16,
                            Opis = "Varazdin -> Cakovec",
                            Polazak = new DateTime(2026, 5, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 9,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 12
                        },
                        new
                        {
                            Id = 21,
                            CijenaPoMjestu = 6.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 19, 7, 35, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 1,
                            Opis = "Jutarnji commute",
                            Polazak = new DateTime(2026, 5, 19, 6, 50, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 19,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 3,
                            VozacId = 14
                        },
                        new
                        {
                            Id = 22,
                            CijenaPoMjestu = 15.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 7,
                            Opis = "Zagreb -> Slavonski Brod",
                            Polazak = new DateTime(2026, 5, 19, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 1,
                            SlobodnaMjesta = 2,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 1
                        },
                        new
                        {
                            Id = 23,
                            CijenaPoMjestu = 23.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 20, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 13,
                            Opis = "Rijeka -> Vukovar",
                            Polazak = new DateTime(2026, 5, 20, 5, 45, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 3,
                            SlobodnaMjesta = 4,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 4
                        },
                        new
                        {
                            Id = 24,
                            CijenaPoMjestu = 9.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 5,
                            Opis = "Split -> Zadar vecernja",
                            Polazak = new DateTime(2026, 5, 20, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 2,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 6
                        },
                        new
                        {
                            Id = 25,
                            CijenaPoMjestu = 10.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 21, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 14,
                            Opis = "Karlovac -> Bjelovar",
                            Polazak = new DateTime(2026, 5, 21, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 8,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 3,
                            VozacId = 8
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.HasOne("SideSeat.Models.Vozilo", "Vozilo")
                        .WithMany()
                        .HasForeignKey("VoziloId");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("SideSeat.Models.OcjenaVoznje", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SideSeat.Models.Placanje", b =>
                {
                    b.HasOne("SideSeat.Models.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SideSeat.Models.Rezervacija", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Putnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PutnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Voznja", "Voznja")
                        .WithMany("Rezervacije")
                        .HasForeignKey("VoznjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Putnik");

                    b.Navigation("Voznja");
                });

            modelBuilder.Entity("SideSeat.Models.Vozilo", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Vlasnik")
                        .WithMany()
                        .HasForeignKey("VlasnikId");

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.HasOne("SideSeat.Models.Grad", "OdredisniGrad")
                        .WithMany()
                        .HasForeignKey("OdredisniGradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Grad", "PolazniGrad")
                        .WithMany()
                        .HasForeignKey("PolazniGradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Korisnik", "Vozac")
                        .WithMany("KreiraneVoznje")
                        .HasForeignKey("VozacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OdredisniGrad");

                    b.Navigation("PolazniGrad");

                    b.Navigation("Vozac");
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.Navigation("KreiraneVoznje");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
