// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SideSeat.Data;

#nullable disable

namespace SideSeat.Migrations
{
    [DbContext(typeof(SideSeatDbContext))]
    [Migration("20260507133043_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SideSeat.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gradovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Drzava = "Hrvatska",
                            Naziv = "Zagreb",
                            PostanskiBroj = "10000"
                        },
                        new
                        {
                            Id = 2,
                            Drzava = "Hrvatska",
                            Naziv = "Split",
                            PostanskiBroj = "21000"
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojMobitela")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoziloId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojMobitela = "0911111111",
                            DatumRegistracije = new DateTime(2026, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marko@example.com",
                            Ime = "Marko",
                            JeAktivan = true,
                            Prezime = "Maric",
                            Tip = 0
                        },
                        new
                        {
                            Id = 2,
                            BrojMobitela = "0922222222",
                            DatumRegistracije = new DateTime(2026, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivana@example.com",
                            Ime = "Ivana",
                            JeAktivan = true,
                            Prezime = "Ivic",
                            Tip = 1
                        },
                        new
                        {
                            Id = 3,
                            BrojMobitela = "0933333333",
                            DatumRegistracije = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            Ime = "Ana",
                            JeAktivan = true,
                            Prezime = "Admin",
                            Tip = 2
                        });
                });

            modelBuilder.Entity("SideSeat.Models.OcjenaVoznje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("BrojZvjezdica")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kreirano")
                        .HasColumnType("datetime2");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("Ocjene");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 2,
                            BrojZvjezdica = 5,
                            Komentar = "Odlicno",
                            Kreirano = new DateTime(2026, 5, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            RezervacijaId = 1
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<bool>("Uspjesno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VrijemePlacanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("Placanja");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Iznos = 15.00m,
                            NacinPlacanja = 1,
                            RezervacijaId = 1,
                            Uspjesno = true,
                            VrijemePlacanja = new DateTime(2026, 5, 2, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojMjesta")
                        .HasColumnType("int");

                    b.Property<decimal>("CijenaUkupno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PutnikId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VoznjaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemeRezervacije")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PutnikId");

                    b.HasIndex("VoznjaId");

                    b.ToTable("Rezervacije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojMjesta = 1,
                            CijenaUkupno = 15.00m,
                            Napomena = "Bez prtljage",
                            PutnikId = 2,
                            Status = 0,
                            VoznjaId = 1,
                            VrijemeRezervacije = new DateTime(2026, 5, 2, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Vozilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojSjedala")
                        .HasColumnType("int");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProsjecnaPotrosnja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Registracija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VlasnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VlasnikId");

                    b.ToTable("Vozila");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Boja = "Siva",
                            BrojSjedala = 5,
                            GodinaProizvodnje = 2021,
                            Marka = "Skoda",
                            Model = "Octavia",
                            ProsjecnaPotrosnja = 6.5m,
                            Registracija = "ZG-1234-AA",
                            VlasnikId = 1
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoMjestu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OcekivaniDolazak")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdredisniGradId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Polazak")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolazniGradId")
                        .HasColumnType("int");

                    b.Property<int>("SlobodnaMjesta")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UkupnoMjesta")
                        .HasColumnType("int");

                    b.Property<int>("VozacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdredisniGradId");

                    b.HasIndex("PolazniGradId");

                    b.HasIndex("VozacId");

                    b.ToTable("Voznje");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CijenaPoMjestu = 15.00m,
                            OcekivaniDolazak = new DateTime(2026, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OdredisniGradId = 2,
                            Opis = "Jutarnja voznja",
                            Polazak = new DateTime(2026, 5, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            PolazniGradId = 1,
                            SlobodnaMjesta = 3,
                            Status = 0,
                            UkupnoMjesta = 4,
                            VozacId = 1
                        });
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.HasOne("SideSeat.Models.Vozilo", "Vozilo")
                        .WithMany()
                        .HasForeignKey("VoziloId");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("SideSeat.Models.OcjenaVoznje", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SideSeat.Models.Placanje", b =>
                {
                    b.HasOne("SideSeat.Models.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SideSeat.Models.Rezervacija", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Putnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PutnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Voznja", "Voznja")
                        .WithMany("Rezervacije")
                        .HasForeignKey("VoznjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Putnik");

                    b.Navigation("Voznja");
                });

            modelBuilder.Entity("SideSeat.Models.Vozilo", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Vlasnik")
                        .WithMany()
                        .HasForeignKey("VlasnikId");

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.HasOne("SideSeat.Models.Grad", "OdredisniGrad")
                        .WithMany()
                        .HasForeignKey("OdredisniGradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Grad", "PolazniGrad")
                        .WithMany()
                        .HasForeignKey("PolazniGradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Korisnik", "Vozac")
                        .WithMany("KreiraneVoznje")
                        .HasForeignKey("VozacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OdredisniGrad");

                    b.Navigation("PolazniGrad");

                    b.Navigation("Vozac");
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.Navigation("KreiraneVoznje");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
