// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SideSeat.Data;

#nullable disable

namespace SideSeat.Migrations
{
    [DbContext(typeof(SideSeatDbContext))]
    partial class SideSeatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SideSeat.Models.Grad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojMobitela")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("bit");

                    b.Property<string>("KycBrojOsobne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KycBrojVozacke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KycDatumRodenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("KycOib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KycPodnesen")
                        .HasColumnType("bit");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoziloId");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("SideSeat.Models.OcjenaVoznje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("BrojZvjezdica")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kreirano")
                        .HasColumnType("datetime2");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("Ocjene");
                });

            modelBuilder.Entity("SideSeat.Models.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("int");

                    b.Property<bool>("Uspjesno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VrijemePlacanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId");

                    b.ToTable("Placanja");
                });

            modelBuilder.Entity("SideSeat.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojMjesta")
                        .HasColumnType("int");

                    b.Property<decimal>("CijenaUkupno")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PutnikId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VoznjaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemeRezervacije")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PutnikId");

                    b.HasIndex("VoznjaId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("SideSeat.Models.SaldoTransakcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPoslije")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoPrije")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("SaldoTransakcije");
                });

            modelBuilder.Entity("SideSeat.Models.Vozilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("BrojSjedala")
                        .HasColumnType("int");

                    b.Property<int>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("ProsjecnaPotrosnja")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Registracija")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int?>("VlasnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VlasnikId");

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoMjestu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OcekivaniDolazak")
                        .HasColumnType("datetime2");

                    b.Property<int>("OdredisniGradId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Polazak")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolazniGradId")
                        .HasColumnType("int");

                    b.Property<int>("SlobodnaMjesta")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UkupnoMjesta")
                        .HasColumnType("int");

                    b.Property<int>("VozacId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdredisniGradId");

                    b.HasIndex("PolazniGradId");

                    b.HasIndex("VozacId");

                    b.ToTable("Voznje");
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.HasOne("SideSeat.Models.Vozilo", "Vozilo")
                        .WithMany()
                        .HasForeignKey("VoziloId");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("SideSeat.Models.OcjenaVoznje", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SideSeat.Models.Placanje", b =>
                {
                    b.HasOne("SideSeat.Models.Rezervacija", "Rezervacija")
                        .WithMany()
                        .HasForeignKey("RezervacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("SideSeat.Models.Rezervacija", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Putnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("PutnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Voznja", "Voznja")
                        .WithMany("Rezervacije")
                        .HasForeignKey("VoznjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Putnik");

                    b.Navigation("Voznja");
                });

            modelBuilder.Entity("SideSeat.Models.SaldoTransakcija", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Korisnik")
                        .WithMany("SaldoTransakcije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("SideSeat.Models.Vozilo", b =>
                {
                    b.HasOne("SideSeat.Models.Korisnik", "Vlasnik")
                        .WithMany()
                        .HasForeignKey("VlasnikId");

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.HasOne("SideSeat.Models.Grad", "OdredisniGrad")
                        .WithMany()
                        .HasForeignKey("OdredisniGradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Grad", "PolazniGrad")
                        .WithMany()
                        .HasForeignKey("PolazniGradId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SideSeat.Models.Korisnik", "Vozac")
                        .WithMany("KreiraneVoznje")
                        .HasForeignKey("VozacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OdredisniGrad");

                    b.Navigation("PolazniGrad");

                    b.Navigation("Vozac");
                });

            modelBuilder.Entity("SideSeat.Models.Korisnik", b =>
                {
                    b.Navigation("KreiraneVoznje");

                    b.Navigation("Rezervacije");

                    b.Navigation("SaldoTransakcije");
                });

            modelBuilder.Entity("SideSeat.Models.Voznja", b =>
                {
                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
